### ISSUE TITLE
IFTTT configuration

### ISSUE THREAD

**Issue by wifi75** [drsprite/OpenSprinkler-Push-Notifications#5]
Hello, sorry but istruction are different for configure IFTTT.
Can you help me?

**Comment by poblabs** [comment]
A little late than never.... not sure how I missed this. 

Are you still having issues?

**Comment by wifi75** [comment]
Not a problem. all work, thank you.
But all message is only in english, how is possible translate in italian language?

**Comment by poblabs** [comment]
You can translate it using the `config.yaml` variables. For example:

```
stations: # Station activity notifications for start and stop. Valid options are "yes" or "no"
  notify:
    start: "yes"
    stop: "yes"
  messages: # Use {} as the place where the station name will be displayed
    start: "{} is now active"
    stop: "{} is now idle" 
```

Under the `messages`, change the words for `start` and `stop` to Italian. You have to keep `{}` though.
